[package]
name = "rx"
version = "0.2.0"
description = "a modern, extensible pixel editor"
license = "GPL-3.0-only"
repository = "https://github.com/cloudhead/rx"
homepage = "https://github.com/cloudhead/rx"
authors = ["Alexis Sellier <self@cloudhead.io>"]
edition = "2018"

[features]
default = ["glfw"]

[dependencies]
pico-args = "0.3.0"
env_logger = { version = "0.6.2", default-features = false, features = ["termcolor"] }
png = { version = "0.15.0" }
gif = "0.10.2"
glfw = { version = "0.34.0", optional = true }
winit = { version = "0.20.0-alpha4", optional = true }
snap = "0.2.5"
log = "0.4.6"
directories = "2.0.2"
meowhash = "0.1.2"
digest = "0.8.1"
nonempty = "0.1"

[dependencies.rgx]
version = "0.3.1"

[dev-dependencies]
lazy_static = "*"
