[package]
name = "rx"
version = "0.1.0"
description = "a modern, extensible pixel editor"
license = "GPL-3.0-only"
repository = "https://github.com/cloudhead/rx"
homepage = "https://github.com/cloudhead/rx"
authors = ["Alexis Sellier <self@cloudhead.io>"]
edition = "2018"

[features]
default = ["glfw"]
vulkan = ["rgx/vulkan"]
metal = ["rgx/metal"]
dx11 = ["rgx/dx11"]
dx12 = ["rgx/dx12"]

[dependencies]
clap = { version = "2.33.0", default-features = false }
cgmath = { version = "0.17.0", default-features = false }
env_logger = { version = "0.6.2", default-features = false, features = ["termcolor"] }
image = { version = "0.21.2", default-features = false, features = ["png_codec"] }
gif = "0.10.2"
glfw = { version = "0.32.0", optional = true }
winit = { version = "0.20.0-alpha3", optional = true }
log = "0.4.6"
directories = "2.0.2"
raw-window-handle = "0.1.0"

[dependencies.rgx]
version = "0.1.2"
