[package]
name = "rx"
version = "0.1.0"
description = "a modern and minimal pixel editor"
license = "GPL-3.0-only"
repository = "https://github.com/cloudhead/rx"
homepage = "https://github.com/cloudhead/rx"
authors = ["Alexis Sellier <alexis@monadic.xyz>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
cgmath = "0.17.0"
env_logger = "0.6.2"
image = { version = "0.21.2", default-features = false, features = ["png_codec"] }
log = "0.4.6"
xdg = "2.2.0"

[dependencies.rgx]
git = "https://github.com/cloudhead/rgx.git"
rev = "master"
version = "*"
